Tms data collection v1
nareshs9/HydraTestAutomation pull request #1
Opened 2024-04-29 20:59 UTC by nareshs9

V1T-TMS-0005	The test measurement system automated data collection script shall have a capability to perform the following:
V1T-TMS-0005 A	The script shall be able to launch and close the Intan RHX software.
V1T-TMS-0005B	The script shall be able to set notch filter to 60Hz.
V1T-TMS-0005C	The script shall be able to create log folder for every run.
V1T-TMS-0005D	The script shall be able to run impedance measurement test multiple times and save impedance measurement test results in the current log folder.
V1T-TMS-0005E	The script shall be able to capture required screens and save it in appropriate log folder.
V1T-TMS-0005F	The script shall be able to select “Sampling Rate” as 20KHz. 
V1T-TMS-0005G	The script shall be able to create and select the appropriate log folder to save the output files on the compute unit that is being recorded.
V1T-TMS-0005H	The script shall be able to start and stop the recording on Intan RHX software. 
V1T-TMS-0005I	The script shall be able to record and store output files for twenty seconds by default. 
V1T-TMS-0005J	The script shall be able to provide an option for user to program the number of impedance test and data recording sessions.

2024-05-01 04:22 UTC, kyle-reed-PN requested changes
In general, the script makes sense to me. Left some comments with questions and suggestions.

2024-05-01 04:22 UTC, kyle-reed-PN commented on TestMeasurementSystem_Layer7V1/Impedance_DataCollection.py
> +        logger.info("Waiting 20 for impedance test to be completed....")
Nit: log says 20, but time.sleep uses 30 in the next line

2024-05-01 04:22 UTC, kyle-reed-PN commented on TestMeasurementSystem_Layer7V1/Impedance_DataCollection.py
> +        logger.info(" close intan application")
Same as other method... Should this log line be commented out since the line above is commented out?

2024-05-01 04:22 UTC, kyle-reed-PN commented on TestMeasurementSystem_Layer7V1/Impedance_DataCollection.py
> +    def startstoprecording(self):
Nit: maybe rename method if only clicking Play and not Record

2024-05-01 04:22 UTC, kyle-reed-PN commented on TestMeasurementSystem_Layer7V1/Impedance_DataCollection.py
> +        move_to = pyautogui.moveTo(self.config_ele.select_to_record[0], self.config_ele.select_to_record[1])
Unclear if clicking play button or record button? The log line above says play button, but the coordinates here are pulled from select_to_record which would make me think it's the record button.

2024-05-02 19:00 UTC, nareshs9 commented on TestMeasurementSystem_Layer7V1/Impedance_DataCollection.py
> +        screenObj = ScreenCapture(self.screens_path, self.window, "save3", True)
Thank you, i changed it to save4

2024-05-02 19:01 UTC, nareshs9 commented on TestMeasurementSystem_Layer7V1/Impedance_DataCollection.py
> +        logger.info(" close intan application")
That's correct, log line shall be either commented or deleted. I am deleting this line.

2024-05-02 19:05 UTC, nareshs9 commented on TestMeasurementSystem_Layer7V1/Impedance_DataCollection.py
> +        logger.info("Waiting 20 for impedance test to be completed....")
Changed the log information from 20 to 30 seconds. Impedance test does take some time between 20 to 30 seconds.

2024-05-02 19:10 UTC, nareshs9 commented on TestMeasurementSystem_Layer7V1/Impedance_DataCollection.py
> +        logger.info(" close intan application")
Deleted the log line.

2024-05-02 19:12 UTC, nareshs9 commented on TestMeasurementSystem_Layer7V1/Impedance_DataCollection.py
> +    def startstoprecording(self):
you are correct, the definition name shall be Play and not record. This definition is meant to start and stop playing and not recording. Changed the name of the definition to startstopplay.

2024-05-15 18:30 UTC, kyle-reed-PN approved these changes

2024-05-31 23:40 UTC, nareshs9 commented
Thank you Divya and Kyle for approving the pull request.

2024-05-31 23:41 UTC, closed without merging